### ISSUE TITLE
Pi Cam V1.3 example raw and result (failed) under Python 3.7

### ISSUE THREAD

**Issue by Coobers** [OsmoSystems/picamraw#8]
If you like to widen support of this lib:
using your example with file location change only using Pi Cam V1.3 I get:

`Traceback (most recent call last):
  File "camx.py", line 6, in <module>
    sensor_mode=0
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/picamraw/main.py", line 26, in __init__
    bayer_array, bayer_order = extract_raw_from_jpeg(filepath, camera_version, sensor_mode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/picamraw/main.py", line 93, in extract_raw_from_jpeg
    raw_bytes = _get_raw_bayer_bytes(jpeg_data_as_bytes, camera_version, sensor_mode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/picamraw/main.py", line 325, in _get_raw_bayer_bytes
    raise ValueError('Unable to locate Bayer data at end of buffer')
ValueError: Unable to locate Bayer data at end of buffer`

![raw](https://user-images.githubusercontent.com/10530408/65965346-c71aec80-e45e-11e9-8c7c-0d3cda58ba5d.jpg)

raw generated with command:
`raspistill --raw -o raw.jpg`

**Comment by thatneat** [comment]
The maintainers only have camera module V2 around to test with, but we would certainly consider a PR to extend support to V1.x modules.
